In [18]:
import numpy as np

In [22]:
m, n = map(int, input().split())
a = [[] for i in range(m)]
b = [[] for i in range(m)]

print("Enter first array")
for i in range(m):
    for j in range(n):
        a[i].append(int(input()))

print("Enter second array")
for i in range(m):
    for j in range(n):
        b[i].append(int(input()))
        
a = np.array(a)
b = np.array(b)

3 3
Enter first array
1
2
3
4
5
6
7
8
9
Enter second array
11
12
13
14
15
16
17
18
19


In [27]:
#dot product of a and b
a@b

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [29]:
#Transpose of a
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [31]:
#Trace of a
a.trace()

15

In [32]:
#Rank of a
np.linalg.matrix_rank(a)

2

In [34]:
#Determinant of a
np.linalg.det(a)

-9.51619735392994e-16

In [37]:
#Inverse of a
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [38]:
#Eigenvalues and eigenvectors
np.linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))